// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnJYXG-v1uRrJAuTD0YdSBnMEGFXAkYwg',
    appId: '1:863587597015:web:1aafd1ca1ce94a04800e92',
    messagingSenderId: '863587597015',
    projectId: 'the-bridge-7cdf0',
    authDomain: 'the-bridge-7cdf0.firebaseapp.com',
    storageBucket: 'the-bridge-7cdf0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCopkKExh-OwmkNG9g9EulgJNHHJCvSTFU',
    appId: '1:863587597015:android:24e33f195d0c9218800e92',
    messagingSenderId: '863587597015',
    projectId: 'the-bridge-7cdf0',
    storageBucket: 'the-bridge-7cdf0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkpW4yNwM839wCmzQlhLJADn5nL2AepM8',
    appId: '1:863587597015:ios:18401770f5559b33800e92',
    messagingSenderId: '863587597015',
    projectId: 'the-bridge-7cdf0',
    storageBucket: 'the-bridge-7cdf0.appspot.com',
    iosBundleId: 'com.example.thebridges',
  );
}
